---
plugin: yc_compute
folders:
  - id_folder
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: "sa.json"
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address

keyed_groups:
  - key: labels.tags